const esbuild = require("esbuild");
const process = require("process");
const builtins = require("builtin-modules");

const banner = `//THIS IS A GENERATED/BUNDLED FILE BY ESBUILD`;

const prod = (process.argv[2] === "production");

async function build() {
	const context = await esbuild.context({
		banner: { js: banner },
		entryPoints: ["./src_ts/main.ts"],
		bundle: true,
		external: ["obsidian", ...builtins],
		format: "cjs",
		target: "es2018",
		logLevel: "info",
		sourcemap: false,
		treeShaking: true,
		outfile: "../Vault/.obsidian/plugins/story-writer/main.js",
	});

	if (prod) {
		await context.rebuild();
		process.exit(0);
	} else {
		await context.watch();
	}
}

build().catch(() => process.exit(1));
