default_model: "Claude 4.5"
model: ""
temperature: 0.8
splitter: "\n****\n"    # Conversation splitter for excluding previous parts
history_path: "chat.md"
add_header: true
chat_with_story: false
use_summary: false
custom_instructions_folder: "./_includes/settings/_instructions/"